name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Install Zig
      #   run: |
      #     ZIG_VERSION="0.11.0"
      #     wget https://ziglang.org/download/$ZIG_VERSION/zig-macos-x86_64-$ZIG_VERSION.tar.xz
      #     tar -xf zig-macos-x86_64-$ZIG_VERSION.tar.xz
      #     echo "$PWD/zig-macos-x86_64-$ZIG_VERSION" >> $GITHUB_PATH
      # - name: Test Zig Installation
      #   run: |
      #     zig version
      # - name: Build
      #   run: zig build
      # - name: Package
      #   run: tar -cJf zig-macos-x86_64-0.11.0.tar.xz zig
      # - name: Upload
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: zig-macos-x86_64-0.11.0.tar.xz
      #     asset_name: zig-macos-x86_64-0.11.0.tar.xz
      #     asset_content_type: application/x-tar
      #     asset_label: Metal-Frameworks 0.11.0 for macOS
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - name: Zip Source Code
        run: |
          git archive --format zip --output source_code.zip HEAD

      - name: Create Tar.gz Source Code
        run: |
          git archive --format tar.gz --output source_code.tar.gz HEAD

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Source Code Zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./source_code.zip
          asset_name: source_code.zip
          asset_content_type: application/zip

      - name: Upload Source Code Tar.gz to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./source_code.tar.gz
          asset_name: source_code.tar.gz
          asset_content_type: application/gzip